# Generated by Django 3.2.3 on 2021-06-28 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('idMoneda', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Moneda')),
                ('nomMoneda', models.CharField(max_length=50, verbose_name='Nombre de la moneda')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('numIdentificacion', models.IntegerField(primary_key=True, serialize=False, verbose_name='Numero de identificacion')),
                ('foto', models.FileField(blank=True, null=True, upload_to='')),
                ('nomCompleto', models.CharField(max_length=100, verbose_name='Nombre proveedor')),
                ('telefono', models.IntegerField(verbose_name='Numero de telefono')),
                ('direccion', models.CharField(max_length=100, verbose_name='Direccion proveedor')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('pais', models.CharField(max_length=100, verbose_name='Pais')),
                ('contraseña', models.CharField(max_length=100, verbose_name='Contraseña')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.moneda')),
            ],
        ),
    ]
