# Generated by Django 3.2.3 on 2021-06-28 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='numIdentificacion',
            field=models.IntegerField(max_length=20, primary_key=True, serialize=False, verbose_name='Numero de identificacion'),
        ),
    ]
