# Generated by Django 3.2.3 on 2021-07-05 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_proveedor_numidentificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='imagen/'),
        ),
    ]
