# Generated by Django 3.2.3 on 2021-07-05 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_proveedor_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='numIdentificacion',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Numero de identificacion'),
        ),
    ]
